In [ ]:
import pandas as pd

In [ ]:
import os
os.listdir("../data")

['baltimore_rh.csv',
 'baltimore_temp.csv',
 'denver_rh.csv',
 'denver_temp.csv',
 'las_vegas_rh.csv',
 'las_vegas_temp.csv',
 'los_angeles_rh.csv',
 'los_angeles_temp.csv',
 'Metadata.xlsx',
 'miami_rh.csv',
 'miami_temp.csv',
 'phoenix_rh.csv',
 'phoenix_temp.csv',
 'portland_rh.csv',
 'portland_temp.csv',
 'README.md',
 'tucson_rh.csv',
 'tucson_temp.csv']

In [ ]:
df.head()

,Date - Time,hour,H16,H17,H18,H19,L17,L18,L20,M16,M18,M19,VH16,VH17,VH18,VH19,VL17,VL18,VL19,VL20
0,7/11/17 0:00,0:00,25.5,25.1,25.1,25.1,25.7,25.6,25.1,26.1,27.1,26.1,25.1,25.1,25.6,25.6,25.6,26.6,27.1,25.1
1,7/11/17 1:00,1:00,25.5,25.6,24.1,24.1,25.7,25.6,25.1,25.1,26.1,25.1,24.1,25.1,25.6,25.6,25.6,25.6,26.1,25.1
2,7/11/17 2:00,2:00,25.5,25.6,23.1,23.6,25.7,25.6,25.1,24.1,26.1,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.1,25.1
3,7/11/17 3:00,3:00,25.5,25.6,22.6,23.1,25.7,25.6,25.1,23.1,26.1,24.6,21.6,25.6,25.6,25.6,25.6,24.6,26.1,25.1
4,7/11/17 4:00,4:00,26.0,25.6,23.6,23.6,25.7,25.6,25.1,24.1,26.6,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.6,25.6

In [ ]:
os.listdir("../data")

['baltimore_rh.csv',
 'baltimore_temp.csv',
 'denver_rh.csv',
 'denver_temp.csv',
 'las_vegas_rh.csv',
 'las_vegas_temp.csv',
 'los_angeles_rh.csv',
 'los_angeles_temp.csv',
 'Metadata.xlsx',
 'miami_rh.csv',
 'miami_temp.csv',
 'phoenix_rh.csv',
 'phoenix_temp.csv',
 'portland_rh.csv',
 'portland_temp.csv',
 'README.md',
 'tucson_rh.csv',
 'tucson_temp.csv']

In [ ]:
df=pd.read_csv("../data/Baltimore Temp.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/Baltimore Temp.csv'

In [ ]:
df=pd.read_csv("../data/Baltimore_Temp.csv")

In [ ]:
df.head()

,Date - Time,hour,H16,H17,H18,H19,L17,L18,L20,M16,M18,M19,VH16,VH17,VH18,VH19,VL17,VL18,VL19,VL20
0,7/11/17 0:00,0:00,25.5,25.1,25.1,25.1,25.7,25.6,25.1,26.1,27.1,26.1,25.1,25.1,25.6,25.6,25.6,26.6,27.1,25.1
1,7/11/17 1:00,1:00,25.5,25.6,24.1,24.1,25.7,25.6,25.1,25.1,26.1,25.1,24.1,25.1,25.6,25.6,25.6,25.6,26.1,25.1
2,7/11/17 2:00,2:00,25.5,25.6,23.1,23.6,25.7,25.6,25.1,24.1,26.1,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.1,25.1
3,7/11/17 3:00,3:00,25.5,25.6,22.6,23.1,25.7,25.6,25.1,23.1,26.1,24.6,21.6,25.6,25.6,25.6,25.6,24.6,26.1,25.1
4,7/11/17 4:00,4:00,26.0,25.6,23.6,23.6,25.7,25.6,25.1,24.1,26.6,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.6,25.6

In [ ]:
df.shape

(1968, 20)

In [ ]:
df.columns

Index(['Date - Time', 'hour', 'H16', 'H17', 'H18', 'H19', 'L17', 'L18', 'L20',
       'M16', 'M18', 'M19', 'VH16', 'VH17', 'VH18', 'VH19', 'VL17', 'VL18',
       'VL19', 'VL20'],
      dtype='object')

In [ ]:
df.dtypes

Date - Time     object
hour            object
H16            float64
H17            float64
H18            float64
H19            float64
L17            float64
L18            float64
L20            float64
M16            float64
M18            float64
M19            float64
VH16           float64
VH17           float64
VH18           float64
VH19           float64
VL17           float64
VL18           float64
VL19           float64
VL20           float64
dtype: object

In [ ]:
df.isnull().sum()

Date - Time    0
hour           0
H16            0
H17            0
H18            0
H19            0
L17            0
L18            0
L20            0
M16            0
M18            0
M19            0
VH16           0
VH17           0
VH18           0
VH19           0
VL17           0
VL18           0
VL19           0
VL20           0
dtype: int64

In [ ]:
df.describe()

,H16,H17,H18,H19,L17,L18,L20,M16,M18,M19,VH16,VH17,VH18,VH19,VL17,VL18,VL19,VL20
count,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000
mean,25.456047,24.150559,23.172917,23.678760,24.081098,24.698831,23.878201,24.556809,24.994309,24.453913,22.893445,24.186128,23.522002,23.522002,25.746850,25.112449,24.994309,24.687652
std,4.650655,4.395468,4.807731,4.687965,4.636824,4.894543,4.529597,5.094343,4.484397,4.973736,4.682295,5.037387,4.722970,4.722970,5.002341,4.836732,4.484397,4.603586
min,14.000000,13.100000,11.100000,11.100000,12.100000,12.600000,12.600000,11.500000,13.600000,12.600000,10.100000,11.600000,11.600000,11.600000,13.600000,13.100000,13.600000,12.600000
25%,22.500000,21.100000,19.600000,20.600000,20.700000,21.600000,21.100000,21.100000,22.100000,21.100000,19.600000,20.600000,20.100000,20.100000,22.600000,22.100000,22.100000,21.600000
50%,25.000000,24.100000,23.100000,23.600000,23.700000,24.100000,23.600000,24.100000,24.600000,24.100000,22.600000,23.600000,23.100000,23.100000,25.100000,24.600000,24.600000,24.600000
75%,28.500000,27.100000,26.600000,27.100000,27.200000,28.100000,26.600000,28.100000,28.100000,27.600000,26.100000,27.600000,26.600000,26.600000,29.100000,28.600000,28.100000,27.600000
max,39.500000,36.100000,36.100000,36.100000,36.100000,38.100000,38.100000,38.500000,37.100000,44.100000,35.100000,39.100000,43.100000,43.100000,43.600000,39.100000,37.100000,38.100000

In [ ]:
df["Date - Time"].min(), df["Date - Time"].max()

('7/11/17 0:00', '9/9/17 9:00')

In [ ]:
df["hour"].unique()

In [ ]:
df.info()

In [1]:
import pandas as pd
df=pd.read_csv("../data/baltimore_temp.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/baltimore_temp.csv'

In [2]:
import os
os.getcwd()

'c:\\Users\\q\\Desktop\\infotact project\\Infotact-major-project\\noteboks'

In [3]:
import os
os.listdir("../data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../data'

In [4]:
import os
os.path.exists("../data")

False

os.listdir("..")

In [6]:
import os
os.listdir("../data")

['baltimore_rh.csv',
 'baltimore_temp.csv',
 'data_dictionary.md',
 'denver_rh.csv',
 'denver_temp.csv',
 'las_vegas_rh.csv',
 'las_vegas_temp.csv',
 'los_angeles_rh.csv',
 'los_angeles_temp.csv',
 'Metadata.xlsx',
 'miami_rh.csv',
 'miami_temp.csv',
 'phoenix_rh.csv',
 'phoenix_temp.csv',
 'portland_rh.csv',
 'portland_temp.csv',
 'README.md',
 'tucson_rh.csv',
 'tucson_temp.csv']

In [7]:
import pandas as pd

df = pd.read_csv("../data/baltimore_temp.csv")
df.head()

,Date - Time,hour,H16,H17,H18,H19,L17,L18,L20,M16,M18,M19,VH16,VH17,VH18,VH19,VL17,VL18,VL19,VL20
0,7/11/17 0:00,0:00,25.5,25.1,25.1,25.1,25.7,25.6,25.1,26.1,27.1,26.1,25.1,25.1,25.6,25.6,25.6,26.6,27.1,25.1
1,7/11/17 1:00,1:00,25.5,25.6,24.1,24.1,25.7,25.6,25.1,25.1,26.1,25.1,24.1,25.1,25.6,25.6,25.6,25.6,26.1,25.1
2,7/11/17 2:00,2:00,25.5,25.6,23.1,23.6,25.7,25.6,25.1,24.1,26.1,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.1,25.1
3,7/11/17 3:00,3:00,25.5,25.6,22.6,23.1,25.7,25.6,25.1,23.1,26.1,24.6,21.6,25.6,25.6,25.6,25.6,24.6,26.1,25.1
4,7/11/17 4:00,4:00,26.0,25.6,23.6,23.6,25.7,25.6,25.1,24.1,26.6,25.1,22.6,25.6,25.6,25.6,25.6,25.1,26.6,25.6

In [8]:
df.mean(numeric_only=True)

H16     25.456047
H17     24.150559
H18     23.172917
H19     23.678760
L17     24.081098
L18     24.698831
L20     23.878201
M16     24.556809
M18     24.994309
M19     24.453913
VH16    22.893445
VH17    24.186128
VH18    23.522002
VH19    23.522002
VL17    25.746850
VL18    25.112449
VL19    24.994309
VL20    24.687652
dtype: float64

In [9]:
df.min(numeric_only=True)

H16     14.0
H17     13.1
H18     11.1
H19     11.1
L17     12.1
L18     12.6
L20     12.6
M16     11.5
M18     13.6
M19     12.6
VH16    10.1
VH17    11.6
VH18    11.6
VH19    11.6
VL17    13.6
VL18    13.1
VL19    13.6
VL20    12.6
dtype: float64

In [10]:
df.max(numeric_only=True)

H16     39.5
H17     36.1
H18     36.1
H19     36.1
L17     36.1
L18     38.1
L20     38.1
M16     38.5
M18     37.1
M19     44.1
VH16    35.1
VH17    39.1
VH18    43.1
VH19    43.1
VL17    43.6
VL18    39.1
VL19    37.1
VL20    38.1
dtype: float64

In [11]:
df.std(numeric_only=True)

H16     4.650655
H17     4.395468
H18     4.807731
H19     4.687965
L17     4.636824
L18     4.894543
L20     4.529597
M16     5.094343
M18     4.484397
M19     4.973736
VH16    4.682295
VH17    5.037387
VH18    4.722970
VH19    4.722970
VL17    5.002341
VL18    4.836732
VL19    4.484397
VL20    4.603586
dtype: float64

In [12]:
df.mean(numeric_only=True).idxmax()

'VL17'

In [13]:
df.mean(numeric_only=True).idxmin()

'VH16'